# Generated by Django 4.1.7 on 2023-03-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default="default/defaultdog.jpg", upload_to="pets/"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=1000)),
                (
                    "animal",
                    models.CharField(
                        choices=[
                            ("DOG", "Dog"),
                            ("CAT", "Cat"),
                            ("RODENT", "Rodent"),
                            ("BIRD", "Bird"),
                            ("REPTILE", "Reptile"),
                        ],
                        max_length=100,
                    ),
                ),
                ("breed", models.CharField(default="Unknown", max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("intake", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["intake"],
            },
        ),
    ]
